### ISSUE TITLE
Concept of Updating Resume

### ISSUE THREAD

**Issue by devinmatte** [RamZallan/resume-review#4]
Right now, when you upload a resume, it's a new entry in the list, and people often just delete their old ones. What would be nice is if there was a way to simply have your resume listed, and clicking in would provide the most recent upload, and a history of past resumes to compare against. I think this would provide a much better interface for showing not only a current resume, but past iterations.
It would also make finding someones resume to review a bit easier.
I'm not saying that someone can only have one type of resume too. If I'm applying for a Software Engineering job vs. an RA position, those are two different resumes and would have their own history

**Comment by devinmatte** [comment]
Easy way to do this, make resume filename unique on the page, and always display the newest resume of that name (by that person)
Then on the resume page create a "Previous Versions" section which will link to the older versions in order of that resume

**Comment by RamZallan** [comment]
I think it may also make sense to have the homepage display one listing per person who's uploaded a resume. Then it would show each iteration of the resumes (likely condensed when a newer version exists, with an option to expand the preview) with the comments shown chronologically. So something like

```
[ Outdated file - click to expand ]
- Comment on old resume
- Another comment
[ Newer version (expanded preview as we currently have) ]
- Lorem ipsum new comment for new version

```

**Comment by devinmatte** [comment]
At the very least one per person on the homepage makes perfect sense. I would have to see the other concept to make an opinion on it

**Comment by RamZallan** [comment]
Resume viewing now shows revisions history! 🎉
